/*
 * Pour le calcul de la methode du disque non graphique
 */
package calculpi;

/**
 *
 * @author Elyan
 */
public class GUI3 extends javax.swing.JFrame {

    /**
     * Creates new form GUI3
     */
    public GUI3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtResultatScrollPane = new javax.swing.JScrollPane();
        txtResultat = new javax.swing.JTextArea();
        btnCalculer = new javax.swing.JButton();
        sliderNbPoints = new javax.swing.JSlider();
        lblNbPoints = new javax.swing.JLabel();
        txtNbPoints = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Calcul Pi : Méthode du quart de disque (non graphique)");
        setResizable(false);

        txtResultat.setEditable(false);
        txtResultat.setColumns(20);
        txtResultat.setRows(5);
        txtResultatScrollPane.setViewportView(txtResultat);

        btnCalculer.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCalculer.setText("Calculer !");
        btnCalculer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculerActionPerformed(evt);
            }
        });

        sliderNbPoints.setMajorTickSpacing(100000);
        sliderNbPoints.setMaximum(1000000);
        sliderNbPoints.setMinimum(100000);
        sliderNbPoints.setPaintTicks(true);
        sliderNbPoints.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderNbPointsStateChanged(evt);
            }
        });

        lblNbPoints.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblNbPoints.setText("Nombre de points :");

        txtNbPoints.setEditable(false);
        txtNbPoints.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNbPoints.setText("100000 pts");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtResultatScrollPane)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sliderNbPoints, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNbPoints)
                        .addGap(31, 31, 31)
                        .addComponent(txtNbPoints))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCalculer, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(183, 183, 183)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtResultatScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sliderNbPoints, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNbPoints)
                        .addComponent(txtNbPoints, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addComponent(btnCalculer)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sliderNbPointsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderNbPointsStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_sliderNbPointsStateChanged

    private void btnCalculerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalculerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculer;
    private javax.swing.JLabel lblNbPoints;
    private javax.swing.JSlider sliderNbPoints;
    private javax.swing.JTextField txtNbPoints;
    private javax.swing.JTextArea txtResultat;
    private javax.swing.JScrollPane txtResultatScrollPane;
    // End of variables declaration//GEN-END:variables
}
